"""
譜面画像をGitHub Pagesで公開するためのHTML生成スクリプト

使い方:
  # 1曲分のHTMLを生成
  python make_page.py chart_output/ --title "曲名 [MASTER]"

  # 複数曲のインデックスページも生成
  python make_page.py chart_output_1/ chart_output_2/ --index

ディレクトリ構成（GitHub Pages用）:
  docs/
  ├── index.html          ← 曲一覧（--index時）
  ├── song1/
  │   ├── index.html      ← 譜面ページ
  │   ├── chart_output_001.png
  │   ├── chart_output_002.png
  │   └── ...
  └── song2/
      └── ...
"""

import argparse
import re
import sys
from pathlib import Path


def collect_images(dir_path: Path) -> list[Path]:
    """ディレクトリ内のPNG画像を番号順にソートして返す"""
    pngs = sorted(dir_path.glob("*.png"),
                  key=lambda p: _extract_number(p.name))
    if not pngs:
        print(f"[ERROR] PNGファイルが見つかりません: {dir_path}")
        sys.exit(1)
    return pngs


def _extract_number(filename: str) -> int:
    """ファイル名から番号を抽出（chart_output_003.png → 3）"""
    m = re.search(r'(\d+)', filename)
    return int(m.group(1)) if m else 0


def generate_chart_html(images: list[Path], title: str, out_dir: Path):
    """譜面画像を縦にくっつけて表示するHTMLを生成"""
    # 画像はout_dirからの相対パスで参照
    img_tags = []
    for img in images:
        # out_dir内にコピー済みならファイル名だけ、そうでなければ相対パス
        rel = img.name if img.parent == out_dir else str(img.relative_to(out_dir))
        img_tags.append(f'    <img src="{rel}" alt="{img.stem}">')

    images_html = "\n".join(img_tags)

    html = f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
      background: #1a1a2e;
      display: flex;
      flex-direction: column;
      align-items: center;
      min-height: 100vh;
    }}
    header {{
      position: sticky;
      top: 0;
      z-index: 10;
      width: 100%;
      background: rgba(26, 26, 46, 0.95);
      backdrop-filter: blur(8px);
      padding: 12px 20px;
      text-align: center;
      border-bottom: 1px solid #333;
    }}
    header h1 {{
      color: #e0e0e0;
      font-size: 18px;
      font-weight: 500;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    .chart-container {{
      width: 100%;
      max-width: 800px;
      display: flex;
      flex-direction: column;
      align-items: center;
    }}
    .chart-container img {{
      display: block;
      width: 100%;
      height: auto;
      /* 画像間の隙間を完全に消す */
      margin: 0;
      padding: 0;
      line-height: 0;
      font-size: 0;
    }}
    .back-link {{
      color: #888;
      text-decoration: none;
      font-size: 14px;
      position: absolute;
      left: 20px;
      top: 50%;
      transform: translateY(-50%);
    }}
    .back-link:hover {{ color: #ccc; }}
    footer {{
      padding: 40px 20px;
      text-align: center;
      color: #555;
      font-size: 12px;
      font-family: sans-serif;
    }}
  </style>
</head>
<body>
  <header>
    <a class="back-link" href="../">← 戻る</a>
    <h1>{title}</h1>
  </header>
  <div class="chart-container">
{images_html}
  </div>
  <footer>Generated by Polaris Code Chart Image Generator</footer>
</body>
</html>"""

    out_file = out_dir / "index.html"
    out_file.write_text(html, encoding="utf-8")
    print(f"[INFO] 生成: {out_file} ({len(images)} 枚)")


def generate_index_html(entries: list[dict], out_dir: Path):
    """複数曲の一覧ページを生成"""
    items = []
    for e in entries:
        items.append(
            f'    <a class="song" href="{e["dir"]}/">'
            f'<span class="song-title">{e["title"]}</span>'
            f'<span class="song-count">{e["count"]} images</span></a>'
        )
    items_html = "\n".join(items)

    html = f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ポラリスコード 譜面保管所</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
      background: #1a1a2e;
      color: #e0e0e0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      min-height: 100vh;
      padding: 40px 20px;
    }}
    h1 {{
      font-size: 24px;
      font-weight: 600;
      margin-bottom: 8px;
    }}
    .subtitle {{
      color: #888;
      font-size: 14px;
      margin-bottom: 32px;
    }}
    .song-list {{
      width: 100%;
      max-width: 600px;
      display: flex;
      flex-direction: column;
      gap: 8px;
    }}
    .song {{
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 14px 20px;
      background: #16213e;
      border: 1px solid #2a2a4a;
      border-radius: 8px;
      color: #e0e0e0;
      text-decoration: none;
      transition: background 0.15s, border-color 0.15s;
    }}
    .song:hover {{
      background: #1a2745;
      border-color: #4a4a7a;
    }}
    .song-title {{ font-size: 15px; }}
    .song-count {{ font-size: 13px; color: #888; }}
  </style>
</head>
<body>
  <h1>ポラリスコード 譜面保管所</h1>
  <p class="subtitle">Polaris Code Chart Archive</p>
  <div class="song-list">
{items_html}
  </div>
</body>
</html>"""

    out_file = out_dir / "index.html"
    out_file.write_text(html, encoding="utf-8")
    print(f"[INFO] インデックス生成: {out_file} ({len(entries)} 曲)")


def main():
    parser = argparse.ArgumentParser(
        description="譜面画像からGitHub Pages用HTMLを生成",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
使用例:
  # 1曲分
  python make_page.py chart_output/ --title "楽曲名 [MASTER]"

  # 複数曲 + インデックス
  python make_page.py song1/ song2/ song3/ --index

  # 出力先を指定（GitHub Pages用のdocsフォルダへ）
  python make_page.py chart_output/ --title "曲名" --docs-dir docs/
""")

    parser.add_argument("dirs", nargs="+", type=Path,
                        help="譜面画像のディレクトリ（複数指定可）")
    parser.add_argument("--title", default=None,
                        help="曲名（1曲の場合）")
    parser.add_argument("--index", action="store_true",
                        help="複数曲のインデックスページも生成")
    parser.add_argument("--docs-dir", type=Path, default=None,
                        help="出力先ディレクトリ (デフォルト: 画像と同じ場所)")

    args = parser.parse_args()

    entries = []

    for chart_dir in args.dirs:
        if not chart_dir.is_dir():
            print(f"[WARN] ディレクトリではありません: {chart_dir}")
            continue

        images = collect_images(chart_dir)
        title = args.title or chart_dir.name

        # 出力先
        if args.docs_dir:
            out_dir = args.docs_dir / chart_dir.name
            out_dir.mkdir(parents=True, exist_ok=True)
            # 既にdocs内にある場合はコピー不要
            if chart_dir.resolve() != out_dir.resolve():
                import shutil
                for img in images:
                    shutil.copy2(img, out_dir / img.name)
                images = sorted(out_dir.glob("*.png"),
                                key=lambda p: _extract_number(p.name))
        else:
            out_dir = chart_dir

        generate_chart_html(images, title, out_dir)
        entries.append({
            "dir": chart_dir.name,
            "title": title,
            "count": len(images),
        })

    # インデックスページ
    if args.index and entries:
        index_dir = args.docs_dir if args.docs_dir else args.dirs[0].parent
        generate_index_html(entries, index_dir)

    print("[DONE] 完了！")


if __name__ == "__main__":
    main()